import webbrowser
from typing import Literal

from pydantic import BaseModel
from textual import on
from textual.app import ComposeResult
from textual.containers import Horizontal
from textual.widget import Widget
from textual.widgets import Button, Label, Markdown, Static

from shotgun.logging_config import get_logger

logger = get_logger(__name__)


class HintMessage(BaseModel):
    message: str
    kind: Literal["hint"] = "hint"
    # Optional email copy functionality
    email: str | None = None
    markdown_after: str | None = None
    # Optional link functionality
    link: str | None = None
    link_text: str | None = None  # Button label, defaults to "Open link"


class HintMessageWidget(Widget):
    """A message for the user generated by shotgun, not the agent.."""

    DEFAULT_CSS = """
        HintMessageWidget {
          background: $secondary-background-darken-1;
          height: auto;
          margin: 1;
          margin-left: 1;
          padding: 1;

          * > Markdown {
              height: auto;
              offset-x: -1;
              padding: 0;
              margin: 0;
          }
        }

        HintMessageWidget .email-copy-row {
            width: auto;
            height: auto;
            margin: 1 0;
        }

        HintMessageWidget .email-text {
            width: auto;
            margin-right: 1;
            content-align: left middle;
        }

        HintMessageWidget .copy-btn {
            width: auto;
            min-width: 12;
        }

        HintMessageWidget #copy-status {
            height: 1;
            width: 100%;
            margin-top: 1;
            content-align: left middle;
        }

        HintMessageWidget .link-row {
            width: auto;
            height: auto;
            margin: 1 0;
        }

        HintMessageWidget .link-text {
            width: auto;
            margin-right: 1;
            content-align: left middle;
        }

        HintMessageWidget .link-btn {
            width: auto;
            min-width: 16;
            margin-right: 1;
        }

        HintMessageWidget #link-status {
            height: 1;
            width: 100%;
            margin-top: 1;
            content-align: left middle;
        }

    """

    def __init__(self, message: HintMessage) -> None:
        super().__init__()
        self.message = message

    def compose(self) -> ComposeResult:
        # Main message markdown
        yield Markdown(markdown=f"{self.message.message}")

        # Optional email copy section
        if self.message.email:
            # Email + copy button on same line
            with Horizontal(classes="email-copy-row"):
                yield Static(f"Contact: {self.message.email}", classes="email-text")
                yield Button("Copy email", id="copy-email-btn", classes="copy-btn")

            # Status feedback label
            yield Label("", id="copy-status")

            # Optional markdown after email
            if self.message.markdown_after:
                yield Markdown(self.message.markdown_after)

        # Optional link section
        if self.message.link:
            button_label = self.message.link_text or "Open link"
            # Link buttons on same line
            with Horizontal(classes="link-row"):
                yield Static(f"{button_label}:", classes="link-text")
                yield Button("Open in browser", id="open-link-btn", classes="link-btn")
                yield Button("Copy link", id="copy-link-btn", classes="link-btn")

            # Status feedback label for link operations
            yield Label("", id="link-status")

    @on(Button.Pressed, "#copy-email-btn")
    def _copy_email(self) -> None:
        """Copy email address to clipboard when button is pressed."""
        if not self.message.email:
            return

        status_label = self.query_one("#copy-status", Label)

        try:
            import pyperclip  # type: ignore[import-untyped]  # noqa: PGH003

            pyperclip.copy(self.message.email)
            status_label.update("✓ Copied to clipboard!")
            logger.debug(
                f"Successfully copied email to clipboard: {self.message.email}"
            )

        except ImportError:
            status_label.update(
                f"⚠️ Clipboard unavailable. Please manually copy: {self.message.email}"
            )
            logger.warning("pyperclip not available for clipboard operations")

        except Exception as e:
            status_label.update(f"⚠️ Copy failed: {e}")
            logger.error(f"Failed to copy email to clipboard: {e}", exc_info=True)

    @on(Button.Pressed, "#open-link-btn")
    def _open_link(self) -> None:
        """Open link in browser when button is pressed."""
        if not self.message.link:
            return

        status_label = self.query_one("#link-status", Label)

        try:
            webbrowser.open(self.message.link)
            status_label.update("✓ Opened in browser!")
            logger.debug(f"Successfully opened link in browser: {self.message.link}")

        except Exception as e:
            status_label.update(f"⚠️ Failed to open browser: {e}")
            logger.error(f"Failed to open link in browser: {e}", exc_info=True)

    @on(Button.Pressed, "#copy-link-btn")
    def _copy_link(self) -> None:
        """Copy link to clipboard when button is pressed."""
        if not self.message.link:
            return

        status_label = self.query_one("#link-status", Label)

        try:
            import pyperclip

            pyperclip.copy(self.message.link)
            status_label.update("✓ Copied to clipboard!")
            logger.debug(f"Successfully copied link to clipboard: {self.message.link}")

        except ImportError:
            status_label.update(
                f"⚠️ Clipboard unavailable. Please manually copy: {self.message.link}"
            )
            logger.warning("pyperclip not available for clipboard operations")

        except Exception as e:
            status_label.update(f"⚠️ Copy failed: {e}")
            logger.error(f"Failed to copy link to clipboard: {e}", exc_info=True)
